services:
  lyric-editor:
    image: fareisa/lyric-editor:v1.0
    restart: unless-stopped
    ports:
      - 6932:80
    environment:
      MUSIC_DIR: /music
      BACKEND_HOST: 127.0.0.1
      BACKEND_PORT: 3000
    volumes:
      - /data-new/music:/music
