services:
  lyric-editor:
    image: lyric-editor:test4
    restart: unless-stopped
    ports:
      - 6932:80
    environment:
      MUSIC_DIR: /music/test
      BACKEND_HOST: 0.0.0.0
      BACKEND_PORT: 3000 
    volumes:
      - /data-new/music:/music/test

